/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetocadastro.view;

import projetocadastro.DAO.UsuarioDAO;
import projetocadastro.core.entity.Usuario;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author fabia
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNome = new javax.swing.JLabel();
        campoNomeCadastro = new javax.swing.JTextField();
        LabelLog = new javax.swing.JLabel();
        campoLoginCadastro = new javax.swing.JTextField();
        LabelSenha = new javax.swing.JLabel();
        campoSenhaCadastro = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        campoEmailCadastro = new javax.swing.JTextField();
        buttonSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelNome1 = new javax.swing.JLabel();
        LabelLog1 = new javax.swing.JLabel();
        LabelSenha1 = new javax.swing.JLabel();
        LabelEmail1 = new javax.swing.JLabel();
        buttonSalvar1 = new javax.swing.JButton();
        campoNomeCad = new javax.swing.JTextField();
        campoSenhaCad = new javax.swing.JTextField();
        campoEmailCad = new javax.swing.JTextField();
        campoLoginCad = new javax.swing.JTextField();

        LabelNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelNome.setText("Nome:");

        campoNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeCadastroActionPerformed(evt);
            }
        });

        LabelLog.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelLog.setText("Login:");

        campoLoginCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginCadastroActionPerformed(evt);
            }
        });

        LabelSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelSenha.setText("Senha:");

        LabelEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelEmail.setText("Email: ");

        campoEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailCadastroActionPerformed(evt);
            }
        });

        buttonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar novo usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LabelNome1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        LabelNome1.setText("Nome:");

        LabelLog1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        LabelLog1.setText("Login:");

        LabelSenha1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        LabelSenha1.setText("Senha:");

        LabelEmail1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        LabelEmail1.setText("Email: ");

        buttonSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSalvar1.setText("Salvar");
        buttonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvar1ActionPerformed(evt);
            }
        });

        campoNomeCad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));
        campoNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeCadActionPerformed(evt);
            }
        });

        campoSenhaCad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));
        campoSenhaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaCadActionPerformed(evt);
            }
        });

        campoEmailCad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));
        campoEmailCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailCadActionPerformed(evt);
            }
        });

        campoLoginCad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));
        campoLoginCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(buttonSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelSenha1)
                                    .addComponent(LabelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelLog1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoSenhaCad)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(campoEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoLoginCad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNomeCad)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome1)
                    .addComponent(campoNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoLoginCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLog1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEmail1)
                            .addComponent(campoEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoSenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelSenha1)))
                .addGap(20, 20, 20)
                .addComponent(buttonSalvar1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeCadastroActionPerformed

    private void campoLoginCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginCadastroActionPerformed

    private void campoEmailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailCadastroActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvar1ActionPerformed


          try {
              
                String nome = campoNomeCad.getText();
                String login = campoLoginCad.getText();
                String senha = campoSenhaCad.getText();
                String email = campoEmailCad.getText();
                
              if (nome.isEmpty() || login.isEmpty() || senha.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos");
            } else {
            
                Usuario novoUsuario = new Usuario();
              novoUsuario.setNome(campoNomeCad.getText());
              novoUsuario.setLogin(campoLoginCad.getText());
              novoUsuario.setEmail(campoEmailCad.getText());
              novoUsuario.setSenha(campoSenhaCad.getText());
              
              new UsuarioDAO().inserir(novoUsuario);
              JOptionPane.showMessageDialog(rootPane, "Cadastro com sucesso!");         
              
              campoNomeCad.setText("");
              campoLoginCad.setText("");
              campoSenhaCad.setText("");
              campoEmailCad.setText("");
              
              dispose();
              
          } 
              } 
              catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar usuário! Revise seus dados." + ex.getMessage());
           }
           

    }//GEN-LAST:event_buttonSalvar1ActionPerformed

    private void campoNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeCadActionPerformed

    private void campoSenhaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaCadActionPerformed

    private void campoEmailCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailCadActionPerformed

    private void campoLoginCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginCadActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEmail1;
    private javax.swing.JLabel LabelLog;
    private javax.swing.JLabel LabelLog1;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNome1;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelSenha1;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JButton buttonSalvar1;
    private javax.swing.JTextField campoEmailCad;
    private javax.swing.JTextField campoEmailCadastro;
    private javax.swing.JTextField campoLoginCad;
    private javax.swing.JTextField campoLoginCadastro;
    private javax.swing.JTextField campoNomeCad;
    private javax.swing.JTextField campoNomeCadastro;
    private javax.swing.JTextField campoSenhaCad;
    private javax.swing.JTextField campoSenhaCadastro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
